add user role
GEKKA888/test pull request #18
Opened 2018-01-05 09:02 UTC by GEKKA888

管理者画面を充実させ、ユーザーにロールを追加できるようにしました

2018-01-05 15:34 UTC, yosm requested changes

2018-01-05 15:34 UTC, yosm commented on app/controllers/admin/users_controller.rb
> +      session[:user_id] = @user.id
ここでsessionを更新するのは問題になりませんか？
管理者の認証ロジックがどこにあるか確認できていませんが、現在ログイン中のユーザーが、新しく作られたユーザーに置き換わってしまいそうに見えます

2018-01-05 15:34 UTC, yosm commented on app/views/admin/users/index.html.erb
> +            <% unless (u.user_type == "admin" && admincounter < 2)%>
ここの処理は回りくどいですね。
先にcontrollerで現在のadminの数を取得して@admin_counter等の名前で保持しておけば、18行目からの処理も必要無いし、簡潔にかけそうです。

また、指示の内容は「管理ユーザが1人もいなくならないように削除の制御をしましょう」ですが、これは言葉通りに実装して良いものでしょうか。
管理画面で自分のアカウントを削除できて良いのか。自分のアカウントを削除すると、どうなってしまうのか。
一つの楽な方法として、この画面を見れるのは管理者のみなのだから、自分のアカウントを削除出来なければ、それだけで管理者が0人になることは防げます。

指示の内容をそのまま実装するのではなく、その実装が他の部分に及ぼす影響を考慮するようにしていきましょう。

2018-01-05 15:34 UTC, yosm commented on app/controllers/admin/users_controller.rb
>      redirect_to admin_users_path
画面を経由せずとも、DELETEメソッドでこのURLを叩くことは可能です。
つまり画面に削除ボタンを出していなくても、このアクションは実行出来てしまいます。
ということは、このアクションの中でも管理者が0人にならないように考慮してあげないと、一つの脆弱性となってしまいます

2018-01-06 07:52 UTC, GEKKA888 commented
修正しました

2018-01-06 08:51 UTC, merged